# Generated by Django 3.2.6 on 2021-10-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='', max_length=50)),
                ('recommend', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=4000)),
            ],
        ),
    ]
